language: android
before_install:
 - chmod +x gradlew
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

script:
   - ./gradlew build connectedCheck